version: '3.8'
services:
  quote-bot:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      - db

  db:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: quotebot
    volumes:
      - './setup.sql:/docker-entrypoint-initdb.d/setup.sql:ro'
      - './sql-data:/var/lib/postgresql/data'
    networks:
      - backend

networks:
  backend:
    driver: bridge
